"""Defense Strategist Agent Node.

Acts as the strategic counter-measure system. Analyzes the
attack generated by the Red Team, cross-references it with the
established medical facts, and provides the human executive
with a "Rebuttal Strategy" to defend the launch plan.
"""

from __future__ import annotations

import logging

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.runnables import RunnableConfig
from langchain_google_genai import ChatGoogleGenerativeAI

from warroom.agents.prompts import TIME_CONSTRAINT_PREAMBLE
from warroom.constants import LLM_MODEL_JUDGE
from warroom.graph.state import WarRoomState

logger = logging.getLogger(__name__)

DEFENSE_PROMPT = (
  TIME_CONSTRAINT_PREAMBLE
  + """
You are the Lead Commercial Strategist defending your oncology launch plan.
A rival "Red Team" has just analyzed your plan and prepared a highly
aggressive counter-attack to use against your sales force.

Your job is to provide Decision Support for the human executive by
drafting a "Defense Memo" that rebuts the Red Team's attack.

Instructions:
1. Analyze the Red Team's counter-attack plan.
2. Cross-reference their attacks with the known Clinical & Medical Facts.
3. For each attack, provide a tactical rebuttal.
   - If they attack your safety profile, defend it with specific clinical nuance
     (e.g., standard of care is worse).
   - If they attack efficacy, find a silver lining from the facts
     (e.g., deeper responses, heavily pre-treated cohort).
4. Output a clean, executive-ready "Defense Memo".
5. Do NOT rewrite the original launch strategy. Your only output is
   this defense document.
"""
)


def defense_strategist_node(state: WarRoomState, config: RunnableConfig) -> dict:
  """Execute the Defense Strategist Agent.

  Args:
    state: Current graph state containing the strategy brief,
      the facts, and the red team's counter plan.
    config: Runnable configuration for tracing.

  Returns:
    State delta with the `defense_rebuttal`.
  """
  logger.info("Executing Defense Strategist Agent...")

  try:
    from langchain_google_genai import HarmBlockThreshold, HarmCategory

    llm = ChatGoogleGenerativeAI(
      model=LLM_MODEL_JUDGE,
      temperature=0.3,
      safety_settings={
        HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
        HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
        HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
        HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
      },
    )

    human_prompt = (
      f"--- Clinical Intelligence (The Facts) ---\n"
      f"{state.get('clinical_intel', 'None')}\n\n"
      f"--- Medical Affairs (The Literature) ---\n"
      f"{state.get('literature_intel', 'None')}\n\n"
      f"--- Our Launch Strategy ---\n"
      f"{state.get('strategy_brief', 'None')}\n\n"
      f"--- RED TEAM ATTACK (The Threat) ---\n"
      f"{state.get('competitor_counter_plan', 'None')}"
    )

    messages = [
      SystemMessage(content=DEFENSE_PROMPT),
      HumanMessage(content=human_prompt),
    ]

    result = llm.invoke(messages, config=config)
    final_output = result.content

    # Flatten list of content blocks if necessary
    if isinstance(final_output, list):
      parts = []
      for item in final_output:
        if isinstance(item, dict) and "text" in item:
          parts.append(str(item["text"]))
        else:
          parts.append(str(item))
      final_output = "\n".join(parts)

    if not isinstance(final_output, str):
      final_output = str(final_output)

    return {"defense_rebuttal": final_output}

  except Exception as e:
    logger.exception("Error in defense_strategist_node")
    return {"defense_rebuttal": f"ERROR in Defense Strategist: {e}"}
