"""WarRoomState definition for the LangGraph pipeline."""

from __future__ import annotations

import operator
from typing import Annotated, Required, TypedDict


class WarRoomState(TypedDict, total=False):
  """State shared across all nodes in the war-room graph.

  Only ``query`` is required at graph invocation. All other
  fields are populated by the agent nodes during execution.

  Attributes:
    query: The original strategic question from the user.
    clinical_intel: The structured report generated by the
      Clinical Intel Agent (based on DB queries).
    literature_intel: The structured report generated by the
      Medical Affairs Agent (based on RAG queries).
    strategy_brief: The final synthesized output from the
      Launch Strategist Agent.
    citations: List of verified PMIDs and NCT IDs extracted
      from the intermediate reports.
    warnings: List of temporal leak warnings detected by the
      validators (used for retry feedback).
    iteration_count: Number of times the pipeline has retried
      due to temporal leaks (max 3).
    compliance_warnings: List of off-label promotional violations
      found by the PRC Agent.
    prc_iteration_count: Number of times the pipeline has retried
      due to PRC violations (max 3).
    ls_iteration_count: Number of times the strategist has retried
      due to temporal leaks (max 2).
    competitor_counter_plan: The adversarial counter-attack strategy
      generated by the Red Team Agent.
    defense_rebuttal: The tactical defense memo created to rebut
      the Red Team's attack.
  """

  query: Required[str]
  clinical_intel: str
  literature_intel: str
  strategy_brief: str
  citations: Annotated[list[str], operator.add]
  warnings: Annotated[list[str], operator.add]
  iteration_count: int
  compliance_warnings: Annotated[list[str], operator.add]
  prc_iteration_count: int
  ls_iteration_count: int
  competitor_counter_plan: str
  defense_rebuttal: str


def new_state(query: str) -> WarRoomState:
  """Create a new WarRoomState with sensible defaults.

  Args:
    query: The user's strategic question.

  Returns:
    A fully initialized WarRoomState.
  """
  return WarRoomState(
    query=query,
    clinical_intel="",
    literature_intel="",
    strategy_brief="",
    citations=[],
    warnings=[],
    iteration_count=0,
    compliance_warnings=[],
    prc_iteration_count=0,
    ls_iteration_count=0,
    competitor_counter_plan="",
    defense_rebuttal="",
  )
